<?php

namespace MOMO\ProjectBundle\Repository;

/**
 * dashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dashRepository extends \Doctrine\ORM\EntityRepository
{
}
